---
name: Term-GnuScreen
version: 0.02
author:
  - 'Mario Domgoergen <dom@math.uni-bonn.de>'
abstract: Control GNU screen via perl
license: perl
resources:
  license: ~
requires:
  File::Temp: 0
  File::Which: 0
  IO::CaptureOutput: 0
  Moose: 0
  Sub::Install: 0
  autodie: 0
build_requires:
  Test::More: 0
provides:
  Term::GnuScreen:
    file: lib/Term/GnuScreen.pm
    version: 0.02
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
